[package]
name = "aoc-input-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
cookie = "0.18.1"
home = "0.5.9"
reqwest = { version = "0.12.9", features = ["cookies"]}
tokio = { version = "1.41.1", features = ["full"] }
