version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/aoc-bins"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/channels-sample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/data-types"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/grrs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/guessing-game"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/hello-world"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/interop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/reading-files"
    schedule:
      interval: "weekly"

