[package]
name = "aoc-private-leaderboard-fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-common = { path = "../aoc-common" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
