name: Build aoc-private-leaderboard-fetch
on:
  pull_request:
    paths:
      - '.github/workflows/aoc-private-leaderboard-fetch.yml'
      - 'aoc-private-leaderboard-fetch/**'
      - 'aoc-common/**'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'aoc-private-leaderboard-fetch'

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo fmt --check
    - run: cargo clippy
    - run: cargo build --release
