name: Build data-types

on:
  pull_request:
    paths:
      - '.github/workflows/data-types.yml'
      - 'data-types/**'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'data-types'

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo fmt --check
    - run: cargo clippy
    - run: cargo test
    - run: cargo build --release
