name: Build grrs

on:
  pull_request:
    paths:
      - '.github/workflows/grrs.yml'
      - 'grrs/**'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'grrs'

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: rustup update
    - run: cargo fmt --check
    - run: cargo clippy
    - run: cargo test
    - run: cargo build --release
