name: Build interop

on:
  pull_request:
    paths:
      - '.github/workflows/interop.yml'
      - 'interop/**'
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'interop'

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo fmt --check
      working-directory: 'interop/multiplier-static'
    - run: cargo fmt --check
      working-directory: 'interop/multiplier-dynamic'
    - run: cargo clippy
      working-directory: 'interop/multiplier-static'
    - run: cargo clippy
      working-directory: 'interop/multiplier-dynamic'
    - run: make all
